services:

  postgres:
    image: postgres:17
    container_name: enterprise_ai_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: enterprise_ai
      POSTGRES_USER: enterprise_user
      POSTGRES_PASSWORD: enterprise_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  qdrant:
    image: qdrant/qdrant:latest
    container_name: enterprise_ai_qdrant
    restart: unless-stopped

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant_data:/qdrant/storage


  redis:
    image: redis:7-alpine
    container_name: enterprise_ai_redis
    restart: unless-stopped

    ports:
      - "6379:6379"


volumes:
  postgres_data:
  qdrant_data: