"""update document metadata

Revision ID: 415d3bf92440
Revises: 77b8c49746ed
Create Date: 2026-09-26 18:49:43.872497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415d3bf92440'
down_revision: Union[str, Sequence[str], None] = '77b8c49746ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('documents', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_name')
    # ### end Alembic commands ###
